(applied_python)[vpalacio@ip-172-30-0-38 ~]$ python
Python 2.7.10 (default, Dec  8 2015, 18:25:23) 
[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 
>>> 
>>> import pysnmp
>>> import paramiko
>>> 
>>> dir (pysnmp)
['__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__', '__version__', 'majorVersionId', 'version', 'x']
>>> dir (paramiko)
['AUTH_FAILED', 'AUTH_PARTIALLY_SUCCESSFUL', 'AUTH_SUCCESSFUL', 'Agent', 'AgentKey', 'AuthHandler', 'AuthenticationException', 'AutoAddPolicy', 'BadAuthenticationType', 'BadHostKeyException', 'BaseSFTP', 'BufferedFile', 'Channel', 'ChannelException', 'ChannelFile', 'DSSKey', 'ECDSAKey', 'GSSAuth', 'GSS_AUTH_AVAILABLE', 'HostKeys', 'InteractiveQuery', 'Message', 'MissingHostKeyPolicy', 'OPEN_FAILED_ADMINISTRATIVELY_PROHIBITED', 'OPEN_FAILED_CONNECT_FAILED', 'OPEN_FAILED_RESOURCE_SHORTAGE', 'OPEN_FAILED_UNKNOWN_CHANNEL_TYPE', 'OPEN_SUCCEEDED', 'PKey', 'Packetizer', 'PasswordRequiredException', 'ProxyCommand', 'ProxyCommandFailure', 'RSAKey', 'RejectPolicy', 'SFTP', 'SFTPAttributes', 'SFTPClient', 'SFTPError', 'SFTPFile', 'SFTPHandle', 'SFTPServer', 'SFTPServerInterface', 'SFTP_BAD_MESSAGE', 'SFTP_CONNECTION_LOST', 'SFTP_EOF', 'SFTP_FAILURE', 'SFTP_NO_CONNECTION', 'SFTP_NO_SUCH_FILE', 'SFTP_OK', 'SFTP_OP_UNSUPPORTED', 'SFTP_PERMISSION_DENIED', 'SSHClient', 'SSHConfig', 'SSHException', 'SecurityOptions', 'ServerInterface', 'SubsystemHandler', 'Transport', 'WarningPolicy', '__all__', '__author__', '__builtins__', '__doc__', '__file__', '__license__', '__name__', '__package__', '__path__', '__version__', '__version_info__', '_version', 'agent', 'auth_handler', 'ber', 'buffered_pipe', 'channel', 'client', 'common', 'compress', 'config', 'dsskey', 'ecdsakey', 'file', 'hostkeys', 'io_sleep', 'kex_gex', 'kex_group1', 'kex_group14', 'kex_gss', 'message', 'packet', 'pipe', 'pkey', 'primes', 'proxy', 'py3compat', 'resource', 'rsakey', 'server', 'sftp', 'sftp_attr', 'sftp_client', 'sftp_file', 'sftp_handle', 'sftp_server', 'sftp_si', 'ssh_exception', 'ssh_gss', 'sys', 'transport', 'util']
>>> 
>>> 
>>> from pprint import pprint 
>>> pprint (dir(pysnmp))
['__builtins__',
 '__doc__',
 '__file__',
 '__name__',
 '__package__',
 '__path__',
 '__version__',
 'majorVersionId',
 'version',
 'x']
>>> pprint (dir(paramiko))
['AUTH_FAILED',
 'AUTH_PARTIALLY_SUCCESSFUL',
 'AUTH_SUCCESSFUL',
 'Agent',
 'AgentKey',
 'AuthHandler',
 'AuthenticationException',
 'AutoAddPolicy',
 'BadAuthenticationType',
 'BadHostKeyException',
 'BaseSFTP',
 'BufferedFile',
 'Channel',
 'ChannelException',
 'ChannelFile',
 'DSSKey',
 'ECDSAKey',
 'GSSAuth',
 'GSS_AUTH_AVAILABLE',
 'HostKeys',
 'InteractiveQuery',
 'Message',
 'MissingHostKeyPolicy',
 'OPEN_FAILED_ADMINISTRATIVELY_PROHIBITED',
 'OPEN_FAILED_CONNECT_FAILED',
 'OPEN_FAILED_RESOURCE_SHORTAGE',
 'OPEN_FAILED_UNKNOWN_CHANNEL_TYPE',
 'OPEN_SUCCEEDED',
 'PKey',
 'Packetizer',
 'PasswordRequiredException',
 'ProxyCommand',
 'ProxyCommandFailure',
 'RSAKey',
 'RejectPolicy',
 'SFTP',
 'SFTPAttributes',
 'SFTPClient',
 'SFTPError',
 'SFTPFile',
 'SFTPHandle',
 'SFTPServer',
 'SFTPServerInterface',
 'SFTP_BAD_MESSAGE',
 'SFTP_CONNECTION_LOST',
 'SFTP_EOF',
 'SFTP_FAILURE',
 'SFTP_NO_CONNECTION',
 'SFTP_NO_SUCH_FILE',
 'SFTP_OK',
 'SFTP_OP_UNSUPPORTED',
 'SFTP_PERMISSION_DENIED',
 'SSHClient',
 'SSHConfig',
 'SSHException',
 'SecurityOptions',
 'ServerInterface',
 'SubsystemHandler',
 'Transport',
 'WarningPolicy',
 '__all__',
 '__author__',
 '__builtins__',
 '__doc__',
 '__file__',
 '__license__',
 '__name__',
 '__package__',
 '__path__',
 '__version__',
 '__version_info__',
 '_version',
 'agent',
 'auth_handler',
 'ber',
 'buffered_pipe',
 'channel',
 'client',
 'common',
 'compress',
 'config',
 'dsskey',
 'ecdsakey',
 'file',
 'hostkeys',
 'io_sleep',
 'kex_gex',
 'kex_group1',
 'kex_group14',
 'kex_gss',
 'message',
 'packet',
 'pipe',
 'pkey',
 'primes',
 'proxy',
 'py3compat',
 'resource',
 'rsakey',
 'server',
 'sftp',
 'sftp_attr',
 'sftp_client',
 'sftp_file',
 'sftp_handle',
 'sftp_server',
 'sftp_si',
 'ssh_exception',
 'ssh_gss',
 'sys',
 'transport',
 'util']
>>>  
... 
>>> print pysnmp.version
(4, 3, 2)
>>> print paramiko.__version__
1.16.0